<?php

namespace App\Console\Commands;

use App\Services\BillingService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Log;

class MacBillingDailyBilling extends Command
{
    protected $signature = 'macbilling:daily-billing {--date= : Run date YYYY-MM-DD for testing}';

    protected $description = 'Auto generate invoices due today and sync invoice statuses';

    public function handle(): int
    {
        $date = $this->option('date');

        $result = BillingService::autoGenerateDueInvoices($date);

        $line = sprintf(
            'date=%s period=%s checked=%s created=%s today=%s catchup=%s existing=%s inactive=%s no_price=%s free_customer=%s future_not_due=%s synced=%s errors=%s',
            $result['date'],
            $result['period'],
            $result['checked'],
            $result['created'],
            $result['created_today'] ?? 0,
            $result['created_missed'] ?? 0,
            $result['existing'],
            $result['inactive'],
            $result['no_price'],
            $result['free_customer'] ?? 0,
            $result['not_due_today'],
            $result['synced'] ?? 0,
            count($result['errors'] ?? [])
        );

        $this->info($line);

        Log::info('MacBilling daily billing: ' . $line, $result);

        if (!empty($result['errors'])) {
            foreach ($result['errors'] as $error) {
                $this->error($error);
            }
        }

        return self::SUCCESS;
    }
}
