<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Invoice;
use App\Models\Customer;
use App\Services\BillingService;
use Illuminate\Http\Request;
use Carbon\Carbon;

class InvoiceController extends Controller
{
    public function preview(Request $request)
    {
        $period = BillingService::cleanPeriod($request->input('period'));
        $rows = BillingService::preview($period);

        $stats = [
            'ready' => $rows->where('can_generate', true)->count(),
            'existing' => $rows->filter(fn ($r) => (bool) $r->existing)->count(),
            'no_price' => $rows->filter(fn ($r) => !$r->existing && $r->customer->status === 'active' && $r->amount <= 0)->count(),
            'inactive' => $rows->filter(fn ($r) => $r->customer->status !== 'active')->count(),
            'total_preview' => $rows->where('can_generate', true)->sum('amount'),
        ];

        return view('admin.invoices.preview', compact('period', 'rows', 'stats'));
    }

    public function generateSelected(Request $request)
    {
        $period = BillingService::cleanPeriod($request->input('period'));
        $ids = (array) $request->input('customer_ids', $request->input('selected', []));

        
        $invoiceBase = $request->is('collector/*') ? '/collector/invoices' : '/admin/invoices';

        if (!$ids) {
            return redirect($invoiceBase . '/preview?period=' . urlencode($period))
                ->with('error', 'Belum ada pelanggan yang dicentang.');
        }

        $result = BillingService::generateSelected($period, $ids);

        $message = 'Generate selesai. Dibuat: ' . $result['created'] .
            ', sudah ada: ' . $result['existing'] .
            ', nonaktif: ' . $result['inactive'] .
            ', gratis: ' . ($result['free_customer'] ?? 0) .
            ', nominal kosong: ' . $result['no_price'] . '.';

        if (!empty($result['errors'])) {
            $message .= ' Error: ' . implode(' | ', array_slice($result['errors'], 0, 3));
        }

        return redirect($invoiceBase . '/preview?period=' . urlencode($period))
            ->with($result['created'] > 0 ? 'success' : 'error', $message);
    }

    public function index(Request $request)
    {
        BillingService::syncStatuses();

        $period = BillingService::cleanPeriod($request->input('period'));
        $status = $request->input('status');

        $invoices = Invoice::with(['customer', 'package'])
            ->when($period, fn ($q) => $q->where('period', $period))
            ->when($status, fn ($q) => $q->where('status', $status))
            ->latest()
            ->paginate(30)
            ->withQueryString();

        return view('admin.invoices.index', compact('invoices', 'period', 'status'));
    }

    public function sync(Request $request)
    {
        $count = BillingService::syncStatuses();
        $period = BillingService::cleanPeriod($request->input('period'));

        return redirect('/admin/invoices?period=' . urlencode($period))
            ->with('success', 'Status invoice disinkronkan. Update: ' . $count . ' invoice.');
    }
    public function autoRun(Request $request)
    {
        $date = $request->input('date');
        $result = BillingService::autoGenerateDueInvoices($date);

        $message = 'Auto billing selesai. Tanggal: ' . $result['date'] .
            ', dibuat: ' . $result['created'] .
            ', hari ini: ' . ($result['created_today'] ?? 0) .
            ', catch-up terlewat: ' . ($result['created_missed'] ?? 0) .
            ', sudah ada: ' . $result['existing'] .
            ', gratis: ' . ($result['free_customer'] ?? 0) .
            ', nominal kosong: ' . $result['no_price'] .
            ', nonaktif: ' . $result['inactive'] .
            ', belum jatuh tempo: ' . ($result['not_due_today'] ?? 0) .
            ', sync status: ' . ($result['synced'] ?? 0) . '.';

        $period = $result['period'] ?? now()->format('Y-m');

        return redirect('/admin/invoices?period=' . urlencode($period))
            ->with('success', $message);
    }



    public function resetCustomerInvoiceData(Request $request, \App\Models\Customer $customer)
    {
        $confirm = trim((string) $request->input('confirm_reset_customer'));

        if ($confirm !== 'RESET TAGIHAN PELANGGAN') {
            return back()->with('error', 'Reset dibatalkan. Kode konfirmasi tidak valid.');
        }

        $backupPath = null;

        try {
            $dbPath = config('database.connections.sqlite.database');

            if ($dbPath && is_string($dbPath) && file_exists($dbPath)) {
                $backupDir = storage_path('app/backups');

                if (!is_dir($backupDir)) {
                    mkdir($backupDir, 0775, true);
                }

                $safeName = preg_replace('/[^A-Za-z0-9_\-]/', '_', (string) $customer->name);
                $backupPath = $backupDir . '/database-before-reset-customer-' . $customer->id . '-' . $safeName . '-' . now()->format('Ymd_His') . '.sqlite';

                copy($dbPath, $backupPath);
            }
        } catch (\Throwable $e) {
            return back()->with('error', 'Backup database gagal dibuat. Reset dibatalkan: ' . $e->getMessage());
        }

        $invoiceCount = 0;
        $paymentCount = 0;

        try {
            \Illuminate\Support\Facades\DB::transaction(function () use ($customer, &$invoiceCount, &$paymentCount) {
                $invoiceIds = \App\Models\Invoice::where('customer_id', $customer->id)->pluck('id')->all();

                $paymentQuery = \App\Models\Payment::where(function ($q) use ($customer, $invoiceIds) {
                    $q->where('customer_id', $customer->id);

                    if (!empty($invoiceIds)) {
                        $q->orWhereIn('invoice_id', $invoiceIds);
                    }
                });

                $paymentCount = (clone $paymentQuery)->count();
                $paymentQuery->delete();

                $invoiceQuery = \App\Models\Invoice::where('customer_id', $customer->id);
                $invoiceCount = (clone $invoiceQuery)->count();
                $invoiceQuery->delete();
            });
        } catch (\Throwable $e) {
            return back()->with('error', 'Reset data tagihan pelanggan gagal: ' . $e->getMessage());
        }

        $msg = 'Data tagihan pelanggan ' . $customer->name . ' berhasil direset. Invoice dihapus: ' . $invoiceCount . ', payment dihapus: ' . $paymentCount . '.';

        if ($backupPath) {
            $msg .= ' Backup database: ' . $backupPath;
        }

        return back()->with('success', $msg);
    }

    public function resetInvoice(Request $request, Invoice $invoice)
    {
        $reason = trim((string) $request->input('reason', 'Reset invoice oleh admin'));

        \Illuminate\Support\Facades\DB::transaction(function () use ($invoice, $reason) {
            \App\Models\Payment::where('invoice_id', $invoice->id)->delete();

            $oldNotes = trim((string) $invoice->notes);
            $resetNote = '[RESET ADMIN ' . now()->format('Y-m-d H:i:s') . '] ' . $reason;

            $invoice->update([
                'paid_amount' => 0,
                'paid_at' => null,
                'payment_method' => null,
                'status' => 'Belum Bayar',
                'notes' => $oldNotes !== '' ? $oldNotes . "\n" . $resetNote : $resetNote,
            ]);
        });

        return back()->with('success', 'Invoice ' . $invoice->invoice_number . ' berhasil direset menjadi Belum Bayar.');
    }

    public function early(Request $request)
    {
        $period = BillingService::cleanPeriod($request->input('period') ?: now()->format('Y-m'));
        $rows = BillingService::preview($period);

        $today = now()->startOfDay();

        $rows = $rows->filter(function ($row) use ($today) {
            return $row->can_generate && \Carbon\Carbon::parse($row->due_date)->startOfDay()->gt($today);
        })->values();

        $stats = [
            'ready' => $rows->count(),
            'total_preview' => $rows->sum('amount'),
        ];

        return view('admin.invoices.early', compact('period', 'rows', 'stats'));
    }

    public function generateEarlySelected(Request $request)
    {
        $period = BillingService::cleanPeriod($request->input('period'));
        $ids = (array) $request->input('customer_ids', $request->input('selected', []));

        
        $invoiceBase = $request->is('collector/*') ? '/collector/invoices' : '/admin/invoices';
if (!$ids) {
            return redirect($invoiceBase . '/early?period=' . urlencode($period))
                ->with('error', 'Belum ada pelanggan yang dicentang.');
        }

        $result = BillingService::generateSelected($period, $ids);

        $message = 'Early invoice selesai. Dibuat: ' . $result['created'] .
            ', sudah ada: ' . $result['existing'] .
            ', nonaktif: ' . $result['inactive'] .
            ', gratis: ' . ($result['free_customer'] ?? 0) .
            ', nominal kosong: ' . $result['no_price'] . '.';

        if (!empty($result['errors'])) {
            $message .= ' Error: ' . implode(' | ', array_slice($result['errors'], 0, 3));
        }

        return redirect($invoiceBase . '/early?period=' . urlencode($period))
            ->with($result['created'] > 0 ? 'success' : 'error', $message);
    }


    public function aging(Request $request)
    {
        BillingService::syncStatuses();

        $q = trim((string) $request->input('q', ''));
        $bucket = trim((string) $request->input('bucket', ''));
        $status = trim((string) $request->input('status', ''));
        $period = trim((string) $request->input('period', ''));

        $today = now()->startOfDay();
        $openStatuses = BillingService::openStatuses();

        $query = Invoice::query()
            ->with(['customer.package', 'customer.odpMaster', 'package'])
            ->whereIn('status', $openStatuses)
            ->when($period !== '', function ($query) use ($period) {
                $query->where('period', $period);
            })
            ->when($status !== '', function ($query) use ($status) {
                $query->where('status', $status);
            })
            ->when($q !== '', function ($query) use ($q) {
                $query->where(function ($sub) use ($q) {
                    $sub->where('invoice_number', 'like', "%{$q}%")
                        ->orWhere('period', 'like', "%{$q}%")
                        ->orWhereHas('customer', function ($customer) use ($q) {
                            $customer->where('name', 'like', "%{$q}%")
                                ->orWhere('phone', 'like', "%{$q}%")
                                ->orWhere('address', 'like', "%{$q}%")
                                ->orWhere('odp', 'like', "%{$q}%")
                                ->orWhere('pppoe_username', 'like', "%{$q}%");
                        });
                });
            });

        $allRows = $query
            ->orderBy('due_date')
            ->orderBy('customer_id')
            ->get()
            ->map(function (Invoice $invoice) use ($today) {
                $dueDate = Carbon::parse($invoice->due_date)->startOfDay();
                $days = $dueDate->diffInDays($today, false);

                if ($days < 0) {
                    $bucket = 'not_due';
                    $bucketLabel = 'Belum Jatuh Tempo';
                    $bucketClass = 'blue';
                } elseif ($days === 0) {
                    $bucket = 'today';
                    $bucketLabel = 'Jatuh Tempo Hari Ini';
                    $bucketClass = 'yellow';
                } elseif ($days <= 30) {
                    $bucket = '1_30';
                    $bucketLabel = 'Lewat 1–30 Hari';
                    $bucketClass = 'yellow';
                } elseif ($days <= 60) {
                    $bucket = '31_60';
                    $bucketLabel = 'Lewat 31–60 Hari';
                    $bucketClass = 'red';
                } else {
                    $bucket = 'over_60';
                    $bucketLabel = 'Lewat >60 Hari';
                    $bucketClass = 'red';
                }

                $invoice->aging_days = $days;
                $invoice->aging_bucket = $bucket;
                $invoice->aging_label = $bucketLabel;
                $invoice->aging_class = $bucketClass;
                $invoice->remaining_amount = max(0, (int) $invoice->amount - (int) $invoice->paid_amount);

                return $invoice;
            });

        $stats = [
            'total_count' => $allRows->count(),
            'total_amount' => $allRows->sum('remaining_amount'),

            'not_due_count' => $allRows->where('aging_bucket', 'not_due')->count(),
            'not_due_amount' => $allRows->where('aging_bucket', 'not_due')->sum('remaining_amount'),

            'today_count' => $allRows->where('aging_bucket', 'today')->count(),
            'today_amount' => $allRows->where('aging_bucket', 'today')->sum('remaining_amount'),

            '1_30_count' => $allRows->where('aging_bucket', '1_30')->count(),
            '1_30_amount' => $allRows->where('aging_bucket', '1_30')->sum('remaining_amount'),

            '31_60_count' => $allRows->where('aging_bucket', '31_60')->count(),
            '31_60_amount' => $allRows->where('aging_bucket', '31_60')->sum('remaining_amount'),

            'over_60_count' => $allRows->where('aging_bucket', 'over_60')->count(),
            'over_60_amount' => $allRows->where('aging_bucket', 'over_60')->sum('remaining_amount'),

            'belum_bayar_count' => $allRows->where('status', 'Belum Bayar')->count(),
            'nunggak_count' => $allRows->where('status', 'Nunggak')->count(),
        ];

        if ($bucket !== '') {
            $allRows = $allRows->where('aging_bucket', $bucket)->values();
        }

        $rows = $allRows->values();

        $periods = Invoice::query()
            ->select('period')
            ->distinct()
            ->orderByDesc('period')
            ->limit(24)
            ->pluck('period');

        return view('admin.invoices.aging', compact('rows', 'stats', 'q', 'bucket', 'status', 'period', 'periods'));
    }


    public function schedule(Request $request)
    {
        BillingService::syncStatuses();

        $period = BillingService::cleanPeriod($request->input('period') ?: now()->format('Y-m'));
        $bucket = trim((string) $request->input('bucket', ''));
        $q = trim((string) $request->input('q', ''));

        $today = now()->startOfDay();

        $customers = Customer::query()
            ->with(['package', 'odpMaster'])
            ->when($q !== '', function ($query) use ($q) {
                $query->where(function ($sub) use ($q) {
                    $sub->where('name', 'like', "%{$q}%")
                        ->orWhere('phone', 'like', "%{$q}%")
                        ->orWhere('address', 'like', "%{$q}%")
                        ->orWhere('odp', 'like', "%{$q}%")
                        ->orWhere('pppoe_username', 'like', "%{$q}%");
                });
            })
            ->orderByRaw('CASE WHEN billing_day IS NULL THEN 99 ELSE billing_day END')
            ->orderBy('name')
            ->get();

        $rows = $customers->map(function (Customer $customer) use ($period, $today) {
            $billingDay = (int) ($customer->billing_day ?: 1);
            $dueDateString = BillingService::dueDate($period, $billingDay);
            $dueDate = Carbon::parse($dueDateString)->startOfDay();

            $existing = Invoice::query()
                ->where('customer_id', $customer->id)
                ->where('period', $period)
                ->first();

            $amountRaw = $customer->monthly_price;
            $amount = (int) $amountRaw;

            $state = 'Akan Datang';
            $stateClass = 'blue';
            $bucket = 'upcoming';
            $canAutoGenerate = false;

            if ($customer->status !== 'active') {
                $state = 'Nonaktif';
                $stateClass = 'red';
                $bucket = 'inactive';
            } elseif ($amountRaw === null || $amountRaw === '' || $amount < 0) {
                $state = 'Nominal Kosong';
                $stateClass = 'yellow';
                $bucket = 'no_price';
            } elseif ($amount === 0) {
                $state = 'Gratis';
                $stateClass = 'blue';
                $bucket = 'free';
            } elseif ($existing) {
                $state = 'Sudah Ada - '.$existing->status;
                $stateClass = match ($existing->status) {
                    'Lunas' => 'green',
                    'Bayar Awal' => 'blue',
                    'Nunggak' => 'red',
                    default => 'yellow',
                };
                $bucket = 'existing';
            } elseif ($dueDate->isSameDay($today)) {
                $state = 'Jatuh Tempo Hari Ini';
                $stateClass = 'green';
                $bucket = 'today';
                $canAutoGenerate = true;
            } elseif ($dueDate->lt($today)) {
                $state = 'Terlewat Belum Dibuat';
                $stateClass = 'red';
                $bucket = 'overdue';
                $canAutoGenerate = false;
            } else {
                $state = 'Menunggu Tanggal Billing';
                $stateClass = 'blue';
                $bucket = 'upcoming';
            }

            return (object) [
                'customer' => $customer,
                'period' => $period,
                'billing_day' => $billingDay,
                'due_date' => $dueDate,
                'days_left' => $today->diffInDays($dueDate, false),
                'amount' => $amount,
                'existing' => $existing,
                'state' => $state,
                'state_class' => $stateClass,
                'bucket' => $bucket,
                'can_auto_generate' => $canAutoGenerate,
            ];
        });

        $stats = [
            'total' => $rows->count(),
            'today' => $rows->where('bucket', 'today')->count(),
            'upcoming' => $rows->where('bucket', 'upcoming')->count(),
            'overdue' => $rows->where('bucket', 'overdue')->count(),
            'existing' => $rows->where('bucket', 'existing')->count(),
            'free' => $rows->where('bucket', 'free')->count(),
            'inactive' => $rows->where('bucket', 'inactive')->count(),
            'no_price' => $rows->where('bucket', 'no_price')->count(),
            'today_amount' => $rows->where('bucket', 'today')->sum('amount'),
            'upcoming_amount' => $rows->where('bucket', 'upcoming')->sum('amount'),
        ];

        if ($bucket !== '') {
            $rows = $rows->where('bucket', $bucket)->values();
        }

        return view('admin.invoices.schedule', compact('period', 'bucket', 'q', 'rows', 'stats'));
    }


    public function detail(Invoice $invoice)
    {
        BillingService::syncStatuses();

        $invoice->load([
            'customer.package',
            'customer.odpMaster',
            'package',
            'payments.collector',
        ]);

        return view('admin.invoices.detail', compact('invoice'));
    }

    public function printInvoice(Invoice $invoice)
    {
        BillingService::syncStatuses();

        $invoice->load([
            'customer.package',
            'customer.odpMaster',
            'package',
            'payments.collector',
        ]);

        return view('admin.invoices.print', compact('invoice'));
    }


    private function invoiceBasePath(): string
    {
        return request()->is('collector/*') ? '/collector/invoices' : $this->invoiceBasePath();
    }

}
